### ISSUE TITLE
`git_duet` recipe should set `duet-commit` as alias for `commit`

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-git#18]
Currently users have to add the following to their `soloistrc`

```yaml
  sprout:
    git:
      global_config:
        'alias.dci': 'duet-commit'
        'alias.drv': 'duet-revert'
        'alias.dmg': 'duet-merge'
        'alias.drb': 'rebase -i --exec "git duet-commit --amend --reset-author"'
```

Based on suggestions from https://github.com/git-duet/git-duet
